sudo: false
language: node_js

# Keep empty to use value from .nvmrc
#node_js: null
node_js: v10.7.0

services:
  - docker

before_install:
  - cp ~/.npmrc .

script:
  #- npm run validate
  - npm run build
  - npm run docker
branches:
  only:
    - master
    - dev 
