language: node_js
node_js:
services:
- docker

script:
- echo $STAGING_URI:22022
- npm run build
- docker build -t krokur-api .

branches:
  only:
  - master
  - dev

addons:
  ssh_known_hosts: 
  - $STAGING_URI:22022
  - $PRODUCTION_URI

before_deploy:
- openssl aes-256-cbc -K $encrypted_c332ac9a4107_key -iv $encrypted_c332ac9a4107_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  #script: rsync -r --delete-after --quiet -e "ssh -p  " $TRAVIS_BUILD_DIR/<dir> travis@$STAGING_URI:~/krokur-api/
  script: ssh $USER@$STAGING_URI [-p 22022] -v exit
  on:
    branch: master