language: node_js
node_js:
services:
- docker

script:
- echo $STAGING_URI:22022
- npm run build
- docker build -t krokur-api .

branches:
  only:
  - master
  - dev

addons:
  ssh_known_hosts: 
  - staging.mikligardur.com:22022
  - krokur.hni.is

before_deploy:
- openssl aes-256-cbc -K $encrypted_c332ac9a4107_key -iv $encrypted_c332ac9a4107_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: docker save $TRAVIS_BUILD_DIR/krokur-api > $TRAVIS_BUILD_DIR/krokur-api.tar; ls -al
  script: rsync -r --delete-after --quiet -e "ssh -p 22022" $TRAVIS_BUILD_DIR/krokur-api.tar travis@$STAGING_URI:~/krokur-api/krokur-api.tar
  #script: ssh $USER@$STAGING_URI -p 22022 -v exit
  on:
    branch: master