sudo: false
language: node_js
node_js: 
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_c332ac9a4107_key -iv $encrypted_c332ac9a4107_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- cp ~/.npmrc .
script:
- npm run build
- docker build -t krokur-api .
branches:
  only:
  - master
  - dev
