sudo: false
language: node_js

# Keep empty to use value from .nvmrc
node_js: null

services:
  - docker

before_install:
  - git clone -b v1 --depth 1 https://$GITHUB_TOKEN@github.com/trustpilot/build-scripts.git
  - build-scripts/travis/init
  - cp ~/.npmrc .

script:
  #- npm run validate
  - npm run build
  - npm run docker
branches:
  only:
    - master
    - dev 
